/**
 * The domain lives in config/site.js and is written into the static files by
 * scripts/sync-domain.js. These tests pin the rewrite itself, because the first
 * version of that script silently corrupted every URL it touched.
 *
 * Usage: node --test test/domain.test.js
 */
const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.join(__dirname, '..');
const site = require('../config/site');
const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');

const STATIC_FILES = [
  'views/index.html', 'views/terms.html', 'views/privacy.html', 'views/404.html',
  'public/robots.txt', 'public/llms.txt', 'public/sitemap.xml',
];

describe('canonical domain', () => {
  it('leaves no reference to a previous host anywhere', () => {
    // A missed canonical points Google at a host that is not yours any more,
    // and a missed mailto sends a refund request into a dead mailbox.
    for (const file of STATIC_FILES) {
      const body = read(file);
      // Only real host references count. A quoted string literal like
      // 'passats.session.v1' is a storage key, and treating it as a stale host
      // is exactly the mistake that destroyed a customer's report.
      const stale = (body.match(/(?<!['"`@\w.])(?:www\.)?passats(?:\.[a-z0-9-]+)*\.[a-z]{2,24}(?![\w@.-])/gi) || [])
        .filter(host => !/^(?:www\.)?passats\.pro$/i.test(host));
      assert.deepEqual(stale, [], `${file} still references ${stale.join(', ')}`);
    }
  });

  it('rewrites a multi-label host without stranding its trailing labels', () => {
    // The bug this file exists for: a single-label pattern turned
    // https://passats.vercel.app/sitemap.xml into https://passats.pro.app/...
    // Every URL still looked plausible, and every one of them was wrong.
    const scratch = fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'passats-domain-'));
    const target = path.join(scratch, 'llms.txt');
    fs.writeFileSync(target, [
      'https://passats.vercel.app/sitemap.xml',
      'https://www.passats.co.uk/privacy',
      'Generated by PassATS · passats.vercel.app · support@passats.vercel.app',
    ].join('\n'));

    // Drive the real script over a copy of the file list it owns.
    const script = path.join(ROOT, 'scripts', 'sync-domain.js');
    const source = fs.readFileSync(script, 'utf8').replace(
      /const FILES = \[[\s\S]*?\];/,
      `const FILES = [${JSON.stringify(path.relative(ROOT, target))}];`,
    );
    const patched = path.join(scratch, 'sync.js');
    fs.writeFileSync(patched, source.replace("require('../config/site')", `require(${JSON.stringify(path.join(ROOT, 'config', 'site.js'))})`));
    execFileSync(process.execPath, [patched], { cwd: ROOT });

    const out = fs.readFileSync(target, 'utf8');
    assert.match(out, /^https:\/\/passats\.pro\/sitemap\.xml$/m, 'multi-label origin');
    assert.match(out, /^https:\/\/passats\.pro\/privacy$/m, 'www and two-part TLD');
    assert.match(out, /passats\.pro · support@passats\.pro$/m, 'bare host and address');
    assert.doesNotMatch(out, /passats\.pro\.[a-z]/, 'no stranded trailing label');
    fs.rmSync(scratch, { recursive: true, force: true });
  });

  it('is idempotent, so CI can use a diff as the drift signal', () => {
    const before = STATIC_FILES.map(read);
    execFileSync(process.execPath, [path.join(ROOT, 'scripts', 'sync-domain.js')], { cwd: ROOT });
    assert.deepEqual(STATIC_FILES.map(read), before, 'a second run must change nothing');
  });

  it('leaves no unfilled placeholder on a legal page', () => {
    // A live legal page reading "[LEGAL ENTITY NAME]" is worse than no page.
    for (const file of ['views/terms.html', 'views/privacy.html']) {
      const body = read(file);
      const left = body.match(/\[[A-Z][A-Z ]{3,}\]/g) || [];
      assert.deepEqual(left, [], `${file} still shows ${left.join(', ')}`);
      assert.doesNotMatch(body, /<strong><\/strong>/, 'an emptied clause left a stray tag');
    }
  });

  it('names the trading entity on both legal pages', () => {
    // EU and UK consumer law requires a paid service to identify the trader.
    for (const file of ['views/terms.html', 'views/privacy.html']) {
      assert.match(read(file), new RegExp(site.LEGAL_ENTITY.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
      assert.match(read(file), new RegExp(site.JURISDICTION.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
    }
  });

  it('can add and remove the registered address, not just delete it once', () => {
    // The first version replaced the whole ` at <strong>[REGISTERED ADDRESS]</strong>`
    // span with an empty string when no address was configured. That deleted the
    // anchor along with the clause, so setting REGISTERED_ADDRESS afterwards
    // changed nothing — an empty diff, no error, and a legal page permanently
    // missing a trader address the law asks for.
    const scratch = fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'passats-addr-'));
    const target = path.join(scratch, 'terms.html');
    const sentence = j => `<p>PassATS is operated by <strong>Acme LLC</strong>, registered in <strong>${j}</strong>. More text.</p>`;
    const script = path.join(ROOT, 'scripts', 'sync-domain.js');
    const run = address => {
      const source = fs.readFileSync(script, 'utf8')
        .replace(/const FILES = \[[\s\S]*?\];/, `const FILES = [${JSON.stringify(path.relative(ROOT, target))}];`)
        .replace("require('../config/site')", `require(${JSON.stringify(path.join(ROOT, 'config', 'site.js'))})`);
      const patched = path.join(scratch, 'sync.js');
      fs.writeFileSync(patched, source);
      execFileSync(process.execPath, [patched], {
        cwd: ROOT,
        env: { ...process.env, REGISTERED_ADDRESS: address },
      });
      return fs.readFileSync(target, 'utf8');
    };

    fs.writeFileSync(target, sentence(site.JURISDICTION));
    const withAddress = run('12 Example St, Wilmington, DE');
    assert.match(withAddress, / at <strong>12 Example St, Wilmington, DE<\/strong>\./, 'address was not added');

    const without = run('');
    assert.doesNotMatch(without, /12 Example St/, 'address was not removed');
    assert.match(without, /registered in <strong>[^<]+<\/strong>\./, 'the sentence must stay well formed');

    // The anchor has to survive the empty pass, or the next set is a no-op.
    const readded = run('9 Second Ave, Dover, DE');
    assert.match(readded, / at <strong>9 Second Ave, Dover, DE<\/strong>\./, 'the anchor did not survive an empty sync');

    fs.rmSync(scratch, { recursive: true, force: true });
  });

  it('serves, links and lists every guide, so none can be orphaned', () => {
    // A guide that exists but is unreachable is worse than no guide: it is
    // dead weight a crawler finds and a reader never can. Adding one to
    // content/guides.js must therefore also route it, sitemap it and link it,
    // and this asserts all three from the single source.
    const guides = require('../content/guides');
    assert.ok(guides.length >= 5, 'expected the guide set to be present');

    const server = read('server.js');
    const sitemapScript = read('scripts/build-sitemap.js');
    const sitemap = read('public/sitemap.xml');
    const home = read('views/index.html');

    // One loop routes them all, so assert the loop rather than each slug.
    assert.match(server, /for \(const guide of require\('\.\/content\/guides'\)\)/, 'guides are not routed');

    for (const guide of guides) {
      const built = path.join(ROOT, 'views', 'guides', `${guide.slug}.html`);
      assert.ok(fs.existsSync(built), `${guide.slug}.html was never built`);
      assert.match(read(`views/guides/${guide.slug}.html`),
        new RegExp(`rel="canonical" href="${site.CANONICAL_ORIGIN}/${guide.slug}"`),
        `${guide.slug} has a wrong canonical`);
      assert.ok(sitemapScript.includes(`'/${guide.slug}'`), `${guide.slug} missing from the sitemap source`);
      assert.ok(sitemap.includes(`${site.CANONICAL_ORIGIN}/${guide.slug}`), `${guide.slug} missing from sitemap.xml`);
      assert.ok(home.includes(`href="/${guide.slug}"`), `${guide.slug} is not linked from the home footer`);
    }
  });

  it('rebuilds guides identically, so CI can use a diff as the drift signal', () => {
    const before = require('../content/guides').map(g => read(`views/guides/${g.slug}.html`));
    execFileSync(process.execPath, [path.join(ROOT, 'scripts', 'build-guides.js')], { cwd: ROOT });
    const after = require('../content/guides').map(g => read(`views/guides/${g.slug}.html`));
    assert.deepEqual(after, before, 'a second build must change nothing');
  });

  it('bundles every file in public/, or they 404 in production', () => {
    // This shipped broken. includeFiles listed views/** only, and Vercel's file
    // tracer does not pull a directory's contents from express.static, so every
    // asset in public/ 404'd in production and fell through to the 404 page.
    // Google reported the sitemap as HTML: it was being served views/404.html.
    //
    // Nothing failed loudly. The legal pages and guides lost tokens.css, and
    // every share preview lost og-image.png, on the day of a launch.
    const vercel = JSON.parse(read('vercel.json'));
    const included = String(vercel.functions?.['api/index.js']?.includeFiles || '');
    for (const dir of ['public', 'views']) {
      assert.ok(included.includes(dir), `includeFiles must bundle ${dir}/**, got ${included}`);
    }
  });

  it('serves every public asset as itself, never as the 404 page', async () => {
    const app = require('../server');
    const supertest = require('supertest');
    const request = supertest(app);
    const expected = {
      '/sitemap.xml': /xml/,
      '/robots.txt': /text\/plain/,
      '/llms.txt': /text\/plain/,
      '/tokens.css': /css/,
      '/favicon.svg': /svg/,
      '/og-image.png': /png/,
    };
    for (const [route, type] of Object.entries(expected)) {
      const res = await request.get(route);
      assert.equal(res.status, 200, `${route} did not serve`);
      assert.match(res.headers['content-type'], type, `${route} served the wrong type`);
      assert.doesNotMatch(String(res.text || ''), /<html/i, `${route} served an HTML page instead of the asset`);
    }
  });

  it('never rewrites a quoted string literal as if it were a hostname', () => {
    // This shipped broken and cost a customer their paid report. The bare-host
    // pattern matched two sessionStorage keys in the client, 'passats.session.v1'
    // and 'passats.anon.v1', and rewrote both to 'passats.pro'. The analytics id
    // and the saved report then shared one key, so the id clobbered the report
    // and JSON.parse threw on reload. The report was gone.
    const scratch = fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'passats-lit-'));
    const target = path.join(scratch, 'sample.html');
    fs.writeFileSync(target, [
      "const STORE_KEY = 'passats.session.v1';",
      "const ANON_KEY = 'passats.anon.v1';",
      'const OTHER = "passats.report.v2";',
      'Generated by PassATS · passats.vercel.app · support@passats.vercel.app',
    ].join('\n'));

    const script = path.join(ROOT, 'scripts', 'sync-domain.js');
    const source = fs.readFileSync(script, 'utf8')
      .replace(/const FILES = \[[\s\S]*?\];/, `const FILES = [${JSON.stringify(path.relative(ROOT, target))}];`)
      .replace("require('../config/site')", `require(${JSON.stringify(path.join(ROOT, 'config', 'site.js'))})`);
    const patched = path.join(scratch, 'sync.js');
    fs.writeFileSync(patched, source);
    execFileSync(process.execPath, [patched], { cwd: ROOT });

    const out = fs.readFileSync(target, 'utf8');
    assert.match(out, /'passats\.session\.v1'/, 'a quoted storage key was rewritten');
    assert.match(out, /'passats\.anon\.v1'/, 'a quoted storage key was rewritten');
    assert.match(out, /"passats\.report\.v2"/, 'a quoted storage key was rewritten');
    // The genuine host in prose must still be rewritten.
    assert.match(out, /PassATS · passats\.pro · support@passats\.pro/, 'a real host mention was missed');
    fs.rmSync(scratch, { recursive: true, force: true });
  });

  it('keeps the browser storage keys distinct', () => {
    // If these ever collide again, the analytics id overwrites the saved report
    // and every customer loses their purchase on refresh.
    const client = read('views/index.html');
    const store = client.match(/const STORE_KEY = '([^']+)'/);
    const anon = client.match(/const ANON_KEY = '([^']+)'/);
    assert.ok(store && anon, 'both storage keys must be present');
    assert.notEqual(store[1], anon[1], `STORE_KEY and ANON_KEY are both '${store[1]}'`);
  });

  it('keeps the support address on the canonical domain', () => {
    assert.equal(site.SUPPORT_EMAIL, `support@${new URL(site.CANONICAL_ORIGIN).hostname}`);
    assert.match(read('views/terms.html'), new RegExp(site.SUPPORT_EMAIL.replace('.', '\\.')));
  });
});
