/**
 * The domain lives in config/site.js and is written into the static files by
 * scripts/sync-domain.js. These tests pin the rewrite itself, because the first
 * version of that script silently corrupted every URL it touched.
 *
 * Usage: node --test test/domain.test.js
 */
const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.join(__dirname, '..');
const site = require('../config/site');
const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');

const STATIC_FILES = [
  'views/index.html', 'views/terms.html', 'views/privacy.html', 'views/404.html',
  'public/robots.txt', 'public/llms.txt', 'public/sitemap.xml',
];

describe('canonical domain', () => {
  it('leaves no reference to a previous host anywhere', () => {
    // A missed canonical points Google at a host that is not yours any more,
    // and a missed mailto sends a refund request into a dead mailbox.
    for (const file of STATIC_FILES) {
      const body = read(file);
      const stale = body.match(/passats\.(?!pro\b)[a-z][a-z0-9.-]*/gi) || [];
      assert.deepEqual(stale, [], `${file} still references ${stale.join(', ')}`);
    }
  });

  it('rewrites a multi-label host without stranding its trailing labels', () => {
    // The bug this file exists for: a single-label pattern turned
    // https://passats.vercel.app/sitemap.xml into https://passats.pro.app/...
    // Every URL still looked plausible, and every one of them was wrong.
    const scratch = fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'passats-domain-'));
    const target = path.join(scratch, 'llms.txt');
    fs.writeFileSync(target, [
      'https://passats.vercel.app/sitemap.xml',
      'https://www.passats.co.uk/privacy',
      'Generated by PassATS · passats.vercel.app · support@passats.vercel.app',
    ].join('\n'));

    // Drive the real script over a copy of the file list it owns.
    const script = path.join(ROOT, 'scripts', 'sync-domain.js');
    const source = fs.readFileSync(script, 'utf8').replace(
      /const FILES = \[[\s\S]*?\];/,
      `const FILES = [${JSON.stringify(path.relative(ROOT, target))}];`,
    );
    const patched = path.join(scratch, 'sync.js');
    fs.writeFileSync(patched, source.replace("require('../config/site')", `require(${JSON.stringify(path.join(ROOT, 'config', 'site.js'))})`));
    execFileSync(process.execPath, [patched], { cwd: ROOT });

    const out = fs.readFileSync(target, 'utf8');
    assert.match(out, /^https:\/\/passats\.pro\/sitemap\.xml$/m, 'multi-label origin');
    assert.match(out, /^https:\/\/passats\.pro\/privacy$/m, 'www and two-part TLD');
    assert.match(out, /passats\.pro · support@passats\.pro$/m, 'bare host and address');
    assert.doesNotMatch(out, /passats\.pro\.[a-z]/, 'no stranded trailing label');
    fs.rmSync(scratch, { recursive: true, force: true });
  });

  it('is idempotent, so CI can use a diff as the drift signal', () => {
    const before = STATIC_FILES.map(read);
    execFileSync(process.execPath, [path.join(ROOT, 'scripts', 'sync-domain.js')], { cwd: ROOT });
    assert.deepEqual(STATIC_FILES.map(read), before, 'a second run must change nothing');
  });

  it('keeps the support address on the canonical domain', () => {
    assert.equal(site.SUPPORT_EMAIL, `support@${new URL(site.CANONICAL_ORIGIN).hostname}`);
    assert.match(read('views/terms.html'), new RegExp(site.SUPPORT_EMAIL.replace('.', '\\.')));
  });
});
